name: cp_delivery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  felix_ui:
    git:
      url: https://github.com/the-flx/FlxUI.git
      ref: 1.0.0
  flx_ui:
    git:
      url: https://github.com/the-flx/FlxUI.git
      ref: 2.0.0-candidate
  get: ^3.26.0
  shimmer: ^1.1.2
  dio: ^3.0.10
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  lint: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: e-Ukraine
      fonts:
        - asset: assets/fonts/e-Ukraine/e-Ukraine-Thin.otf
          weight: 100
        - asset: assets/fonts/e-Ukraine/e-Ukraine-UltraLight.otf
          weight: 200
        - asset: assets/fonts/e-Ukraine/e-Ukraine-Light.otf
          weight: 300
        - asset: assets/fonts/e-Ukraine/e-Ukraine-Regular.otf
          weight: 400
        - asset: assets/fonts/e-Ukraine/e-Ukraine-Medium.otf
          weight: 500
        - asset: assets/fonts/e-Ukraine/e-Ukraine-Bold.otf
          weight: 700
